"""
llm_client.py

Provider-agnostic client for the KSC Ops Assistant, following the same
real+mock idiom as ksc_collection_tracker's traccar_client.py /
erpnext_client.py: a real client per provider, a MockLLMClient with the
same interface, and build_client() that picks based on config presence.

Both real clients use plain requests.post() against each vendor's raw
REST API -- no openai/anthropic SDK dependency, since this bench's
Python env doesn't have them installed and two REST calls don't
justify the weight.

Unlike erpnext_client.build_client()'s reachability probe, this
build_client() does NOT make a live test call to decide is_live --
that would burn a real (billed) request just to render a badge. It
checks config presence only; a real-provider call that then fails at
request time is caught by the caller (assistant_api.ask) and degraded
to the mock for that single response.
"""

from __future__ import annotations

import json

import frappe
import requests


class OpenAIClient:
    API_URL = "https://api.openai.com/v1/chat/completions"

    def __init__(self, api_key: str, model: str = "gpt-4o-mini", timeout: int = 20):
        self.api_key = api_key
        self.model = model
        self.timeout = timeout

    def ask(self, question: str, context: dict) -> str:
        resp = requests.post(
            self.API_URL,
            headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
            json={
                "model": self.model,
                "messages": [
                    {"role": "system", "content": _system_prompt(context)},
                    {"role": "user", "content": question},
                ],
                "temperature": 0.2,
                "max_tokens": 500,
            },
            timeout=self.timeout,
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"].strip()


class AnthropicClient:
    API_URL = "https://api.anthropic.com/v1/messages"

    def __init__(self, api_key: str, model: str = "claude-3-5-haiku-20241022", timeout: int = 20):
        self.api_key = api_key
        self.model = model
        self.timeout = timeout

    def ask(self, question: str, context: dict) -> str:
        resp = requests.post(
            self.API_URL,
            headers={
                "x-api-key": self.api_key,
                "anthropic-version": "2023-06-01",
                "Content-Type": "application/json",
            },
            json={
                "model": self.model,
                "max_tokens": 500,
                "system": _system_prompt(context),
                "messages": [{"role": "user", "content": question}],
            },
            timeout=self.timeout,
        )
        resp.raise_for_status()
        return resp.json()["content"][0]["text"].strip()


def _system_prompt(context: dict) -> str:
    return (
        "You are a read-only operations assistant for KSC's dairy/produce "
        "collection fleet. Answer ONLY from the JSON data below -- never "
        "invent vehicles, drivers, or dates not present in it. If the data "
        "doesn't answer the question, say so.\n\n"
        f"DATA:\n{json.dumps(context, default=str)}"
    )


class MockLLMClient:
    """Deterministic, template-based responder over the SAME real context
    dict the real clients would have been given (gathered once by
    assistant_api.get_context() via frappe.get_list() -- never
    frappe.get_all() -- so it reflects the caller's own permissions).
    Keyword-matches the question against real Collection Run / Leave
    Application data, like MockTraccarClient generates plausible-but-fake
    GPS instead of a generic "I'm a mock" stub."""

    _DISCLAIMER = (
        "\n\n_(mock assistant -- no LLM provider configured; answer "
        "generated by template matching against live Collection Run / "
        "Leave Application data, not a language model.)_"
    )

    def ask(self, question: str, context: dict) -> str:
        q = question.lower()
        if "sla" in q or "breach" in q:
            body = self._sla(context)
        elif "leave" in q:
            body = self._leave(context)
        elif "vehicle" in q or "fleet" in q or "dispatch" in q:
            body = self._fleet(context)
        elif "driver" in q:
            body = self._drivers(context)
        else:
            body = self._overview(context)
        return body + self._DISCLAIMER

    def _sla(self, ctx: dict) -> str:
        breaches = ctx["sla_breaches"]
        if not breaches:
            return f"No SLA breaches in Collection Run records from {ctx['window']['from']} to {ctx['window']['to']}."
        lines = [
            f"- {r['name']}: vehicle {r['vehicle']} (driver {r['driver']}), "
            f"run date {r['run_date']}, station {r['station']}"
            for r in breaches
        ]
        return (
            f"{len(breaches)} SLA Breach run(s) between {ctx['window']['from']} "
            f"and {ctx['window']['to']}:\n" + "\n".join(lines)
        )

    def _leave(self, ctx: dict) -> str:
        rows = ctx["leave_today"]
        if not rows:
            return f"No approved leave applications cover today ({ctx['today']})."
        lines = [
            f"- {r['employee_name']} ({r['employee']}), {r['leave_type']}, "
            f"{r['from_date']} to {r['to_date']}"
            for r in rows
        ]
        return f"{len(rows)} employee(s) on approved leave today ({ctx['today']}):\n" + "\n".join(lines)

    def _fleet(self, ctx: dict) -> str:
        lines = [
            f"- {v['plate_or_tag']}: home station {v['home_station']}, "
            f"default driver {v['default_driver']}"
            for v in ctx["fleet"]
        ]
        return f"{len(ctx['fleet'])} vehicle(s) on record:\n" + "\n".join(lines)

    def _drivers(self, ctx: dict) -> str:
        return self._fleet(ctx)  # same source data, vehicle-centric view

    def _overview(self, ctx: dict) -> str:
        c = ctx["counts"]
        return (
            f"In the last 7 days ({ctx['window']['from']} to {ctx['window']['to']}): "
            f"{c['total_runs']} runs, {c['delivered']} delivered, {c['in_progress']} in progress, "
            f"{c['sla_breaches']} SLA breaches, across {c['vehicles']} vehicles and "
            f"{c['stations']} stations. {c['on_leave_today']} employee(s) on leave today."
        )


def build_client() -> tuple[object, bool]:
    """Reads config the Frappe way (frappe.conf, backed by site_config.json
    / bench set-config), never a .env file. Returns (client, is_live)."""
    provider = (frappe.conf.get("ksc_llm_provider") or "").lower()
    api_key = frappe.conf.get("ksc_llm_api_key")
    model = frappe.conf.get("ksc_llm_model")

    if provider == "openai" and api_key:
        return OpenAIClient(api_key, model=model or "gpt-4o-mini"), True
    if provider == "anthropic" and api_key:
        return AnthropicClient(api_key, model=model or "claude-3-5-haiku-20241022"), True
    return MockLLMClient(), False
